- hosts: all
  gather_facts: true
  vars:
    ansible_aws_ssm_timeout: 3000
    ansible_aws_ssm_profile: default
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-south-1
    ansible_aws_ssm_bucket_name: aieze-prod

  tasks:
    - name: Cleaning Log files
      shell: bbb-conf --clean
