- hosts: all
  gather_facts: yes
  vars:
    ansible_aws_ssm_timeout: 3000
    ansible_aws_ssm_profile: default
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-south-1
    ansible_aws_ssm_bucket_name: aieze-prod
    branch_name: feature/webcam_avatar
    git_username: narsimachilkuri-at-166274191221
    git_password: VO4bfY7r316OiKVwAzGiiMfruM8hEV0Da3%2FdCRktDTY%3D
    git_repo_name: aieze-bbb

  tasks:
    - name: Checkout Latest Code
      ansible.builtin.git:
        repo: https://{{ git_username }}:{{ git_password }}@git-codecommit.ap-south-1.amazonaws.com/v1/repos/{{ git_repo_name }}
        dest: /home/ubuntu/{{ git_repo_name }}
        version: "{{ branch_name }}"
        force: yes

    - name: Change Kurento wsUrl
      shell: yq w -i /home/ubuntu/{{ git_repo_name }}/bigbluebutton-html5/private/config/settings.yml 'public.kurento.wsUrl' wss://{{ vc_domain }}/bbb-webrtc-sfu
    - name: Install Meteor
      shell: curl https://install.meteor.com/ | sh

    - name: Deploy Latest Aieze BBB code
      shell: bash /home/ubuntu/{{ git_repo_name }}/bigbluebutton-html5/deploy_to_usr_share.sh
      become: true
