- hosts: all
  gather_facts: yes
  become: yes
  vars:
    vc_servers: []
    ansible_aws_ssm_timeout: 3000
    ansible_aws_ssm_profile: default
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-south-1
    ansible_aws_ssm_bucket_name: aieze-prod
    vc_maintenance_email: "narsimachilkuri237@gmail.com"
    turn_server: "turn.aieze.in"
    turn_server_secret: "f167c5441530592cfe737811f0145c9e"

  tasks:
    - name: Install BBB with Let's Encrypt certificate
      shell: wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | sudo bash -s -- -w -v focal-260 -s {{ vc_domain }} -e {{ vc_maintenance_email }} -c {{ turn_server }}:{{ turn_server_secret }}
      become: true

    - name: Remove BBB Demo
      ansible.builtin.apt:
        name: bbb-demo
        state: absent
      notify:
      - Restart Bigbluebutton

        #- name: Copy configuration files 
        #copy: src={{ item.src }} dest={{ item.dest }}
        #with_items:
        #- { src: '../vc_config/settings.yml', dest: '/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml' }
        #- { src: '../vc_config/conference.conf.xml', dest: '/opt/freeswitch/conf/autoload_configs/conference.conf.xml' }

        #- name: Replace Domain in settings.yaml
        #replace:
        #path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
        #regexp: 'domain_name'
        #replace: '{{ vc_domain }}'
        #notify: 
        #- Restart Bigbluebutton

        #- name: Store VC Secret
        #shell: cat /etc/bigbluebutton/bbb-web.properties | grep securitySalt | cut -d= -f2
        #register: vc_secret

      #- name: List of VC servers data
      #set_fact:
      # vc_servers: "{{ vc_servers: }} + [ { 'vc_secret': {{ vc_secret }},
      #                   'vc_domain': {{ vc_domain }} }] ]" 
    
      #- name: Creating Scalelite configuration
      #template:
      #  src: vc_config/scalelite.j2
      #  dest: vc_config/scalelite.yml
      #  mode: 0775
      #delegate_to: localhost

  handlers:
    - name: Restart Bigbluebutton
      command: bbb-conf --restart
      become: true
