- hosts: all
  gather_facts: yes
  vars:
    vc_servers: []
    bbb_version: focal-260-2.6.0-alpha.4
    ansible_aws_ssm_timeout: 3000
    ansible_aws_ssm_profile: default
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-south-1
    ansible_aws_ssm_bucket_name: aieze-prod
    vc_maintenance_email: "narsimachilkuri237@gmail.com"
    turn_server: "turn.aieze.in"
    turn_server_secret: "f167c5441530592cfe737811f0145c9e"
    branch_name: feature/webcam_avatar
    git_username: narsimachilkuri-at-166274191221
    git_password: VO4bfY7r316OiKVwAzGiiMfruM8hEV0Da3%2FdCRktDTY%3D
    git_repo_name: aieze-bbb

  tasks:
    - name: Install BBB with Let's Encrypt certificate
      shell: wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | sudo bash -s -- -w -v {{ bbb_version }} -s {{ vc_domain }} -e {{ vc_maintenance_email }} -c {{ turn_server }}:{{ turn_server_secret }}
      become: true
    
    - name: Remove BBB Demo
      ansible.builtin.apt:
        name: bbb-demo
        state: absent
      become: true
   
    - name: Checkout Latest Code
      ansible.builtin.git:
        repo: https://{{ git_username }}:{{ git_password }}@git-codecommit.ap-south-1.amazonaws.com/v1/repos/{{ git_repo_name }}
        dest: /home/ubuntu/{{ git_repo_name }}
        version: "{{ branch_name }}"
        force: yes

    - name: Change Kurento wsUrl
      shell: yq w -i /home/ubuntu/{{ git_repo_name }}/bigbluebutton-html5/private/config/settings.yml 'public.kurento.wsUrl' wss://{{ vc_domain }}/bbb-webrtc-sfu

    - name: Install Meteor
      shell: curl https://install.meteor.com/ | sh

    - name: Deploy Latest Aieze BBB code
      shell: bash /home/ubuntu/{{ git_repo_name }}/bigbluebutton-html5/deploy_to_usr_share.sh
      become: true

    - name: Replacing Favicon
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: 'assets/images/favicon.ico', dest: '/var/www/bigbluebutton-default/assets/favicon.ico' }
      - { src: 'assets/index.html', dest: '/var/www/bigbluebutton-default/assets/index.html' }
      become: true

    - name: Removing Default Presentation
      shell: rm /var/www/bigbluebutton-default/assets/default.pdf
      become: true

    - name: Take Backup of Audio Conference File
      shell: cp /opt/freeswitch/conf/autoload_configs/conference.conf.xml /opt/freeswitch/conf/autoload_configs/conference.conf.xml.bak
      become: true

    - name: Copy Audio conference file
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: '../vc_config/conference.conf.xml', dest: '/opt/freeswitch/conf/autoload_configs/conference.conf.xml' }
      become: true

    - name: Replace Content of Sip Nginx
      shell: sed -i 's/http:/https:/g; s/5066/7443/g' /usr/share/bigbluebutton/nginx/sip.nginx
      become: true
      notify:
      - Restart Freeswitch
      - Restart Bigbluebutton

  handlers:
    - name: Restart Bigbluebutton
      command: bbb-conf --restart
      become: true

    - name: Restart Freeswitch
      command: service freeswitch restart
      become: true
